### ISSUE TITLE
Term description filter do_shortcode works only if admin is logged in

### ISSUE THREAD

**Issue by gauravpadia** [bungeshea/visual-term-description-editor#2]
Hello @bungeshea 

Thanks for this plugin. I found one bug, term_description() filter "do_shortcode" only  works if admin is logged in or any user who have publish_posts capability. This is because in class constructor you have a condition checking if user do not have "publish_posts" capabilities then return and this "do_shortcode" filter is added after it so it only works when admin is logged in.

Please fix this. Thanks.

Kind Regard,
Gaurav Padia

**Comment by bungeshea** [comment]
Thanks for letting me know about this, I completely missed it. I've fixed this in 5ec7d291190bb07fe2eb50838523d51c4226cf8f and will release version 1.3.1 on the WordPress.org repository as soon as I can get SVN working.
